### PR TITLE
Added username details feature

### PR DESCRIPTION
**Pull request by akshgpt7**
Use by adding argument ```-u username``` to stardox.
Fetches most details on the github profile page of a username.
Issue #32.

### CODE REVIEW

**Comment by akshgpt7** [comment]
@0xPrateek Kindly review.

**Comment by 0xPrateek** [comment]
Kindly, rebase your project and structure your code with new modular structure of stardox code.

**Comment by akshgpt7** [comment]
I've made this an independent feature with an action class, because it does not involve fetching stargazer information.

**Comment by 0xPrateek** [comment]
can you implement it without using calss ?

**Comment by akshgpt7** [comment]
I think since it is independent of other functionalities, it can be easily distinguished using class, and doesn't affect any other part. Also, this way it can be easily called without adding extra ```if-else``` statements.

However, if you still want it implemented without class, let me know.

**Comment by 0xPrateek** [comment]
Currently, we don't kneed this feature in stardox

**Pull request closed without merging**
