### PR TITLE
Multithreading and Code structure

### PR DESCRIPTION
**Pull request by CaineArdayfio**
I'm in progress on the multithreading (please don't pull changes just yet, still a WIP).  To implement multi-threading, the functions to get the user data and print it must all be modular. Previously, nearly all the functions and processes were running on a while loop that relied on a `count` and `pos` variable. I took these out (and had to edit some of the suppl. files like Data and Struct) in order to make it completely modular. It still runs sequentially but now I can get it to run as threads (since its modular)

### CODE REVIEW

**Comment by CaineArdayfio** [comment]
It took quite a few hours but I implemented multithreading and it is about a factor of 3 times fasters. You can barely even see the text moving across the screen! I'm still tidying it up, but should the multithreading be implemented via an optional flag or something? I don't see why a user wouldn't want it as it gives a drastic performance boost.

**Comment by CaineArdayfio** [comment]
I've completely finished the multi-threading in the email sender. I had to make a few structural changes to the code, namely moving some of the structer.py lists to the local functional call (as is necessary for multi-threading w/o locking). Can somebody help me merge the multi-threading with the main.

**Comment by 0xPrateek** [comment]
> I'm in progress on the multithreading (please don't pull changes just yet, still a WIP). To implement multi-threading, the functions to get the user data and print it must all be modular. Previously, nearly all the functions and processes were running on a while loop that relied on a `count` and `pos` variable. I took these out (and had to edit some of the suppl. files like Data and Struct) in order to make it completely modular. It still runs sequentially but now I can get it to run as threads (since its modular)

Great..! You got it right. I'll review it very soon and help you in merging.
Which competition you had participated in? ( Just want to know because this project is under open source competion)

**Comment by CaineArdayfio** [comment]
I'm not currently doing any open source competitions right now mainly because I'm a student and I'm a beginner to git contributing but I've done hacktoberfest and a few other things. I'm probably going to start a project of my own soon. What competition are you in?

**Pull request merged**
